package tw.com.soyong.mebook;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mebook
//  @ File Name : BasicUnicode.java
//  @ Date : 2010/4/30
//  @ Author : Victor
//
//

public class BasicUnicode<T> extends SyBook<T> {
	
	static final String ARTICLE = "BAUNI"; 

	public BasicUnicode(int encMode) {
		super(encMode);
	}
	
	public SyItem getData(String id, int mode, final SyInputStream is) throws MebookException {
		
		SyItem syItem = null;
		if ( 0 == id.compareTo(MebookData.ARTICLE) && DATA_TXT == mode){
			
			final SyTreeNode<T> node = findNode(ARTICLE , FIND_LEAF);
				
	        if (null != node ) {
	            T item = node.getData();
	            if ( !SyItem.isNode((SyItem)item) ){
	            	byte [] data = getLeafData((SyItem)item , is);    // decryptData inside getLeafData()
	            	
	            	SyDecrypt.decrypt(mEncMode, data);
	                syItem = new SyItem(data , (SyItem)item );
	            }
	        }	
		} else if ( 0 == id.compareTo(MebookData.FRAME_TABLE) ){		// get frame table
			final SyTreeNode<T> node = findNode(MebookData.FRAME_TABLE , FIND_LEAF);
			
	        if (null != node ) {
	            T item = node.getData();
	            if ( !SyItem.isNode((SyItem)item) ){
	            	byte [] data = getLeafData((SyItem)item , is);    // decryptData inside getLeafData()
	            	
					if ( mEncMode > 0 && mEncMode < 3){
						SyDecrypt.decrypt(mEncMode, data);
					}	            	
	                syItem = new SyItem(data , (SyItem)item );
	            }
	        }
		}else {
			syItem = super.getData(id, mode, is);
		}
		
		return syItem;
	}	
	
	public SyItem getData(String id, int mode) throws MebookException {
		
		SyItem syItem = null;
		if ( 0 == id.compareTo(MebookData.ARTICLE) && DATA_TXT == mode){
			
			final SyTreeNode<T> node = findNode(ARTICLE , FIND_LEAF);
				
	        if (null != node ) {
	            T item = node.getData();
	            if ( !SyItem.isNode((SyItem)item) ){
	            	byte [] data = getLeafData((SyItem)item);    // decryptData inside getLeafData()
	            	
	            	SyDecrypt.decrypt(mEncMode, data);
	                syItem = new SyItem(data , (SyItem)item );
	            }
	        }				
		} else {
			syItem = super.getData(id, mode);
		}
		
		return syItem;
	}

	@Override
	protected T getT() {
		return null;
	}

}
