package tw.com.soyong.mebook;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mebook
//  @ File Name : MebookData.java
//  @ Date : 2009/3/23
//  @ Author : Victor
//
//

public abstract class MebookData {
	
	public static final String ARTICLE	= "ARTICLE";	// get mebook rtf content
	public static final String FRAME_TABLE = "FRMTBL";
	
	int mEncMode ;
	
	public MebookData(int encMode) {
		mEncMode = encMode ;
	}
	
	public void load(final String file , final long pos , final int size){}
	public void load(final SyInputStream is , final long pos , final int size){}
	
	
	public static final int DATA_UNKNOW = 0;
	public static final int DATA_TXT	= 1;
	public static final int DATA_IMG	= 2;
	public static final int IMG_COUNT	= 3;
	
	public abstract SyItem getData(String id , int mode) throws MebookException ;
	public SyItem getData(String id , int mode, final SyInputStream is) throws MebookException {return null;};
}
