package tw.com.soyong.mebook;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mebook
//  @ File Name : MebookInfo.java
//  @ Date : 2009/3/23
//  @ Author : Victor
//
//

public class MebookInfo {
	
	static final String DVD2ME	= "BK_DVD2ME";
	static final String BOOK2ME = "BK_BK2ME";
	static final String MUSIC2ME= "BK_MU2ME";
	public static final String JP_BASIC = "BK_BASICU";
	
	public static final String SUPER_KEY = "0000000000";

	public static final int UNKONW_ID = 0 ;
	public static final int DVD2ME_ID = 1 ;
	public static final int BOOK2ME_ID = 2 ;
	public static final int MUSIC2ME_ID = 3 ;
	public static final int KEY_OPEN_ID = 4 ;
	public static final int KEY_LOCK_ID = 5 ;

	
	public String mFileName;
	public String mTitle;
	public String mID;		// content ID
	public String mBookID;	// book ID
	public int mKeyState;
	public int mRating;
	
	public int mType;
	public ArrayList<Long> mDataSize;
	public ArrayList<Long> mHeaderPosition;
	
	
	public MebookInfo() {
		mDataSize = new ArrayList<Long>(); 
		mHeaderPosition = new ArrayList<Long>();  
		mKeyState = -1 ;
		mRating = 0 ;
	}
	

	/*
	 *  Note always all this function after setup keyState
	 */
	public int getStateID() throws MebookException{
		
		if ( -1 == mKeyState){
			throw new MebookException();
		}
		
		int ret = UNKONW_ID ;
		if ( 0 == mBookID.compareTo(DVD2ME)){
			ret = DVD2ME_ID;
		} else if ( 0 == mBookID.compareTo(BOOK2ME)){
			ret = BOOK2ME_ID;
		} else if ( 0 == mBookID.compareTo(MUSIC2ME)){
			ret = MUSIC2ME_ID;
		} else {
			if ( 0 ==mID.compareTo(SUPER_KEY)||
				 SyProfile.OK == mKeyState ){
				ret = KEY_OPEN_ID;
			} else {
				ret = KEY_LOCK_ID;
			}
		}		
		return ret;
	}
}
