package tw.com.soyong.mebook;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mebook
//  @ File Name : SyChapter.java
//  @ Date : 2009/3/23
//  @ Author : Victor
//
//

public class SyChapter /*extends SyContent*/ {
	public int mNo;
	public int mSentenceIndex;
	public String mName;

	public SyChapter() {
	}
}
