package tw.com.soyong.mebook;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mebook
//  @ File Name : SyContent.java
//  @ Date : 2009/3/23
//  @ Author : Victor
//
//

public class SyContent {
	public ArrayList<SyChapter> mChapter;		// Chapters
	private ArrayList<SySentence> mArticle;		// Sentences
	public SyPostscript mPostscript;
	public SyTime<Integer> mEosTime ;
	
	public SyContent() {
		mChapter = new ArrayList<SyChapter>();
		mArticle = null;
		
		mPostscript = new SyPostscript();
		mEosTime = new SyTime<Integer>(0); 
	}
	
	public final void addSentence( SySentence sentence ){
		
		if ( null == mArticle){
			mArticle = new ArrayList<SySentence>();
		}		
		
		mArticle.add( sentence);
	}
	
	public final int getTotalSentence(){
		
		if ( null == mArticle){
			mArticle = new ArrayList<SySentence>();
			return -1 ;
		}
		
		return mArticle.size();
	}
	
	//
	// **Note** after get arr, mArticle will be destroy
	//
	public final void getSentenceArr( SySentence [] arr ){
		mArticle.toArray(arr);
		
		mArticle.clear();
		mArticle = null;
	}
	
	public final int getEosTime(){
		return mEosTime.getValue();
	}
}
