package tw.com.soyong.mebook;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mebook
//  @ File Name : SyDecrypt.java
//  @ Date : 2009/3/23
//  @ Author : Victor
//
//

public class SyDecrypt {
	static public void decrypt(int mode, byte[] buffer) {
	
        if ( 1 == mode || 3 == mode){
        	final int bufLen = buffer.length;
            for (int k=0; k<bufLen; k++){
                buffer[k] ^= 0x80;
            }
        } else if ( 2 == mode || 4 == mode){
            final String szMode2Key = "VICTORDARCHENGKEVINJACKCHRISJASON"; // key for encode mode 2
			int nKeyLength = szMode2Key.length();
			for (int k = 0; k < buffer.length; k++) {
				buffer[k] ^= szMode2Key.charAt(k % nKeyLength);
			}
        }
	}
	
	private SyDecrypt() {
	}
}
