package tw.com.soyong.mebook;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mebook
//  @ File Name : SyImageBook.java
//  @ Date : 2009/3/23
//  @ Author : Victor
//
//

public class SyImageBook<T> extends SyBook<T> {
	public SyImageBook(int encMode) {
		super(encMode);
	}
	
	public SyItem getData(String id) {
		return null;
	
	}

	@Override
	protected T getT() {
		return null;
	}
}
