package tw.com.soyong.mebook;

import java.io.FileInputStream;
import java.io.IOException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mebook
//  @ File Name : SyProfileHeader.java
//  @ Date : 2009/3/23
//  @ Author : Victor
//
//

public class SyProfileHeader {
	
	static final int HD_SIZE = 14 ;
	
//    String mTag ;      //char szSoyongTag[4];	// 'V''R''P''F'
    int mTotalEntryNo;       //unsigned char szTotalEntryNo[2];		//lpProfileHeader->szTotalEntryNo[0]*10 + lpProfileHeader->szTotalEntryNo[1];
    int mValidEntryNo;      //unsigned char szValidEntryNo[2];		//lpProfileHeader->szValidEntryNo[0]*10 + lpProfileHeader->szValidEntryNo[1];
    int mTotalSerialNo;      //unsigned char szTotalSerialNo[2];		//lpProfileHeader->szTotalSerialNo[0]*10 + lpProfileHeader->szTotalSerialNo[1];
    int mValidValue;         //unsigned char chValidValue;
    int mProfileVersion;     //unsigned char chProfileVersion;
    int mProfileSerialNo;    //unsigned short nProfileSerialNo;      // serial number for this profile
    //unsigned char szReserved[26];	
	
	public SyProfileHeader() {
	}
	
	final void load(final FileInputStream is) throws MebookException, IOException{
		
		byte[] data = new byte [HD_SIZE];
		is.read( data );
		
		byte[] tag = new byte[SyProfile.TAG_SIZE];
		System.arraycopy(data, 0, tag, 0, 4);
		
		String syTag = new String(tag); 
		if (0 != syTag.compareTo(SyProfile.SY_PRO_TAG)) {
			throw new MebookException("Not a SyProfile");
		}
		
		mTotalEntryNo = data[4] * 10 + data[5];
		mValidEntryNo = data[6] * 10 + data[7];
		mTotalSerialNo = data[8] * 10 + data[9];
		mValidValue = data[10];
		mProfileVersion = data[11];
		mProfileSerialNo = data[13] << 8 | data[12];
	}
}
