package tw.com.soyong.mebook;

import java.util.ArrayList;
import java.util.BitSet;
import java.util.HashMap;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mebook
//  @ File Name : SySentence.java
//  @ Date : 2009/3/23
//  @ Author : Victor
//
//

public class SySentence /*extends SyContent*/ {
	public SyTime<Integer> mBeginTime;
	public SyTime<Integer> mEndTime;
	public HashMap<Integer, String> mData;
	public BitSet mFlag;
	public int mChapterIndex;
	public ArrayList<SyVocInfo> mVocInfo;
	public String [] mHlt;
//	public int mPsIndex;
	
	public SySentence() {
		mData = new HashMap<Integer, String>();
		mFlag = new BitSet();
		mVocInfo = new ArrayList<SyVocInfo>();
	}
	
	final public void setData( Integer key , String value){
		
		mData.put(key, value);
		mFlag.set(key);
	}
	
	final public boolean isDataValid( Integer key){
		return mFlag.get(key);
	}
	
	final public int getBeginTime(){
		return mBeginTime.getValue();
	}
	
	final public int getEndTime(){
		return mEndTime.getValue();
	}
	
	final public boolean isValidExtInfo() {

		if ((null != mVocInfo && mVocInfo.size() > 0)
				|| isDataValid(MebookToken.TOK_SYN)
				|| isDataValid(MebookToken.TOK_ANT)
				|| isDataValid(MebookToken.TOK_EXT)) {
			return true;
		}
		return false;
	}	
	
	final public boolean isValidPic() {
		return true == isDataValid(MebookToken.TOK_PIC);
	}	
	
}
