package tw.com.soyong.mebook;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mebook
//  @ File Name : SyTime.java
//  @ Date : 2009/3/23
//  @ Author : Victor
//
//

public class SyTime<T> {
	public T value;
	
	public SyTime() {
	}
	
	public SyTime(T t) {
		value = t ;
	}
	
	public void setValue(T t){
		value = t ;
	}
	
	public T getValue() {
		return value;
	}
	
	public String toString(){
		return String.valueOf(value);
	}
}
