package tw.com.soyong.mebook;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Mebook
//  @ File Name : SyTreeNode.java
//  @ Date : 2009/3/23
//  @ Author : Victor
//
//

public class SyTreeNode<T> {
	T mData;
	SyTreeNode<T> mParent;
	ArrayList<SyTreeNode<T>> mChildren;
	
	public SyTreeNode(T item) {
		mData = item;
	}
	
	public void addChild(SyTreeNode<T> child) {

        if ( null == mChildren ) {
        	mChildren = new ArrayList<SyTreeNode<T>>();
        }
        mChildren.add(child);
        child.setParent(this);		
		
	}
	
	final public ArrayList<SyTreeNode<T>> getChildren() {
        if ( null == mChildren) {
            return new ArrayList<SyTreeNode<T>>();
        }
		return mChildren;
	}
	
	public T getData() {
		return mData;
	}
	
	public int getNumberOfChildren() {
        if ( null == mChildren ) {
            return 0;
        }
        return mChildren.size();
	}
	
	final public SyTreeNode<T> getParent() {
		return mParent;
	}
	
	public void insertChildAt(int index, SyTreeNode<T> child) {
        if ( index == getNumberOfChildren() ) {
            // this is really an append.
            addChild(child);
        } else {
        	mChildren.add(index, child);
        }
        child.setParent(this);
	}
	
	public void removeChildAt(int index) {
		 mChildren.remove(index);
	}
	
	public void setChildren(ArrayList<SyTreeNode<T>> children) {
		mChildren = children;
	}
	
	final public void setData(T data) {
		mData = data;
	}
	
	public void setParent(SyTreeNode<T> parent) {
		mParent = parent ;
	}
	
//	public String toString() {
//		return null;
//	}
}
